global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'payments'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - 'payments:8484'